### PR TITLE
#177: Verify that clock in container is in sync with host

### LINKED ISSUE #177: Verify that clock in container is in sync with host
Exasol-Testcontainers relies on the clocks of the host and the container being in sync, e.g. when checking timestamps in log files.

If the clocks are not in sync this may cause timeouts waiting for startup or bucketfs file uploads.

Docker containers use the clock of their host. But when you run the tests not on the docker host (e.g. on macOS where the docker host is a Linux virtual machine in VirtualBox) this might be an issue.

To make debugging these situations easier, the test framework should check if the clock of the container is in sync and fail with a helpful error message, telling the user to set the clock or use NTP.

### PR DESCRIPTION
**Pull request by redcatbear**
Closes #177.

### CODE REVIEW

File: src/test/java/com/exasol/containers/ContainerSynchronizationVerifierIT.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+
+    // [itest->req~clock-synchronization~1]
+    @Test
+    void testDetectUnsynchronizedClocks() throws ExasolContainerException {
+        final ContainerSynchronizationVerifier verifier = ContainerSynchronizationVerifier.create(CONTAINER);
+        try {
+            CONTAINER.execInContainer("date", "-s01/01/2000 00:00:00");
+            assertThrows(ContainerLaunchException.class, () -> verifier.verifyClocksInSync());
+        } catch (UnsupportedOperationException | IOException exception) {
+            fail("Unable to create intentional offset for sync test.");
```
Comment (kaklakariada) [inline src/test/java/com/exasol/containers/ContainerSynchronizationVerifierIT.java:28]: Throw an AssertionFailed exception with `exception` as cause. Else you won't get any helpful information for debugging the issue.
Or just omit the try-catch.

**Review by kaklakariada — CHANGES_REQUESTED** [review]

**Review by kaklakariada — DISMISSED** [review]

File: src/main/java/com/exasol/containers/ContainerSynchronizationVerifier.java [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+    public static ContainerSynchronizationVerifier create(final ContainerTimeService timeService) {
+        return new ContainerSynchronizationVerifier(timeService);
+    }
+
+    /**
+     * Create a synchronization verifier for a given container.
+     *
+     * @param timeService service that provides the container time
+     */
+    public ContainerSynchronizationVerifier(final ContainerTimeService timeService) {
```
Comment (kaklakariada) [inline src/main/java/com/exasol/containers/ContainerSynchronizationVerifier.java:30]:
```suggestion
    ContainerSynchronizationVerifier(final ContainerTimeService timeService) {
```
Should only be used in unit test

File: src/main/java/com/exasol/containers/ContainerSynchronizationVerifier.java [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+public class ContainerSynchronizationVerifier {
+    private final ContainerTimeService timeService;
+
+    /**
+     * Create a new {@link ContainerSynchronizationVerifier}.
+     *
+     * @param timeService service that provide the time in the container
+     * @return new {@link ContainerSynchronizationVerifier} instance
+     */
+    public static ContainerSynchronizationVerifier create(final ContainerTimeService timeService) {
```
Comment (kaklakariada) [inline src/main/java/com/exasol/containers/ContainerSynchronizationVerifier.java:21]: To simplify usage: get a `Container` as argument and create the `ContainerTimeService` here.

File: src/test/java/com/exasol/containers/ContainerSynchronizationVerifierTest.java [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+        final ContainerSynchronizationVerifier verifier = ContainerSynchronizationVerifier.create(this.timeServiceMock);
+        assertDoesNotThrow(() -> verifier.verifyClocksInSync());
+    }
+
+    // [itest->req~clock-synchronization~1]
+    @Test
+    void testDetectUnsynchronizedClocks() throws ExasolContainerException {
+        Mockito.when(this.timeServiceMock.getTime()).thenReturn(Instant.EPOCH);
+        final ContainerSynchronizationVerifier verifier = ContainerSynchronizationVerifier.create(this.timeServiceMock);
+        assertThrows(ContainerLaunchException.class, () -> verifier.verifyClocksInSync());
```
Comment (kaklakariada) [inline src/test/java/com/exasol/containers/ContainerSynchronizationVerifierTest.java:33]: Verify exception message

**Review by kaklakariada — CHANGES_REQUESTED** [review]

File: src/main/java/com/exasol/containers/ContainerSynchronizationVerifier.java (hunk 3 above)
Comment (redcatbear) [reply src/main/java/com/exasol/containers/ContainerSynchronizationVerifier.java:21]: That breaks the abstraction in my eyes. At the moment the Verifier does not need to know what a container is, only that the time service exists and that it needs one.

File: src/test/java/com/exasol/containers/ContainerSynchronizationVerifierTest.java (hunk 4 above)
Comment (redcatbear) [reply src/test/java/com/exasol/containers/ContainerSynchronizationVerifierTest.java]: Added.

File: src/main/java/com/exasol/containers/ContainerSynchronizationVerifier.java (hunk 2 above)
Comment (redcatbear) [reply src/main/java/com/exasol/containers/ContainerSynchronizationVerifier.java]: Made private. There is not much point in having it open when you have a factory method.

File: src/test/java/com/exasol/containers/ContainerTimeServiceIT.java [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+        final Duration offset = Duration.between(Instant.now(), containerTime);
+        final Duration maxOffset = Duration.ofSeconds(1);
+        assertThat(offset, lessThanOrEqualTo(maxOffset));
+    }
+
+    @Test
+    void testGetMillisSinceEpochUtc() {
+        final long containerTime = service.getMillisSinceEpochUtc();
+        final long offset = System.currentTimeMillis() - containerTime;
+        assertTrue(Math.abs(offset) <= ExasolContainerConstants.MAX_ALLOWED_CLOCK_OFFSET_IN_MILLIS);
```
Comment (kaklakariada) [inline src/test/java/com/exasol/containers/ContainerTimeServiceIT.java:41]: Maybe use a different assertion that gives better feedback in case of failure like in the test above

File: src/test/java/com/exasol/containers/ContainerTimeServiceTest.java [hunk 6]
```diff
@@ -0,0 +1,78 @@
...
+
+    // The ExecResult class has a hidden constructor, so we need reflection to stub the class.
+    private ExecResult createExecResultStub(final int exitCode, final String stdout, final String stderr) {
+        try {
+            final Class<?> resultClass = Class.forName("org.testcontainers.containers.Container$ExecResult");
+            final Constructor<?> constructor = resultClass.getDeclaredConstructor(int.class, String.class,
+                    String.class);
+            constructor.setAccessible(true);
+            final ExecResult resultStub = (ExecResult) constructor.newInstance(exitCode, stdout, stderr);
+            return resultStub;
```
Comment (kaklakariada) [inline src/test/java/com/exasol/containers/ContainerTimeServiceTest.java:54]:
```suggestion
            return (ExecResult) constructor.newInstance(exitCode, stdout, stderr);
```

**Review by kaklakariada — CHANGES_REQUESTED** [review]

File: src/test/java/com/exasol/containers/ContainerTimeServiceIT.java (hunk 5 above)
Comment (redcatbear) [reply src/test/java/com/exasol/containers/ContainerTimeServiceIT.java]: Used `BigDecimal` and `closeTo` to improve assertion.

**Review by kaklakariada — APPROVED** [review]

File: src/test/java/com/exasol/containers/ContainerTimeServiceIT.java (hunk 5 above)
Comment (kaklakariada) [reply src/test/java/com/exasol/containers/ContainerTimeServiceIT.java]: Nice! Again what learned :-D
