### PR TITLE
#56: DatabaseService::start() does not wait until database is ready for connections

### LINKED ISSUE #56: DatabaseService::start() does not wait until database is connectible
After calling `DatabaseService::start`, `Container::getJdbcConnection`may still produce a `connection refused`error if the test is too quick.

### Expected behavior
`start`returns when the database is usable, or throws an Exception.

Easiest way to do so would probably be to call `JdbcDatabaseContainer::waitUntilContainerStarted` internally.

### PR DESCRIPTION
**Pull request by redcatbear**
Closes #56.

### CODE REVIEW

File: src/main/java/com/exasol/containers/ExasolContainer.java [hunk 1]
```diff
@@ -250,9 +260,11 @@ protected void waitUntilContainerStarted() {
             new UdfContainerWaitStrategy(this.detectorFactory).waitUntilReady(this);
             this.readyServices.add(ExasolService.UDF);
         }
+        logger().info("Exasol container started after waiting for the following services to become available: {}",
+                this.requiredServices);
     }
 
-    private void waitUntilCluterConfigurationAvailable() {
+    protected void waitUntilCluterConfigurationAvailable() {
```
Comment (morazow) [inline src/main/java/com/exasol/containers/ExasolContainer.java:267]:
```suggestion
    protected void waitUntilClusterConfigurationAvailable() {
```
