### PR TITLE
Bug/82 exposed ports

### LINKED ISSUE #82: addExposedPorts overrides default ports
addExposedPorts currently overrides the default ports, that are required to access the database.

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #82

### CODE REVIEW

File: src/main/java/com/exasol/containers/ExasolContainer.java [hunk 1]
```diff
@@ -127,28 +142,27 @@ public int getDefaultInternalDatabasePort() {
...
             return DEFAULT_CONTAINER_INTERNAL_BUCKETFS_PORT_V7_AND_ABOVE;
         } else {
             return DEFAULT_CONTAINER_INTERNAL_BUCKETFS_PORT;
         }
     }
 
-    private void exposePorts() {
-        if (this.getExposedPorts().isEmpty()) {
-            this.addExposedPorts(getDefaultInternalDatabasePort(), getDefaultInternalBucketfsPort());
+    public static class CouldNotDetectPortException extends UnsupportedOperationException {
```
Comment (morazow) [inline src/main/java/com/exasol/containers/ExasolContainer.java:161]:
```suggestion
    public static class PortDetectionException extends UnsupportedOperationException {
```

File: src/main/java/com/exasol/containers/ExasolContainer.java [hunk 2]
```diff
@@ -99,24 +106,32 @@ public ExasolContainer() {
...
+        if (this.portAutodetectFailed) {
+            if (getExposedPorts().isEmpty()) {
+                throw new IllegalArgumentException(
+                        "Could not detect internal ports for custom image. Please specify the port explicitly using withExposedPorts().");
+            } else {
+                logger().warn("Could not detect internal ports for custom image. "
+                        + "Don't forget to expose the database and BucketFs ports yourself.");
+            }
+        }
+        logger().debug("Exposing ports: {}", this.getExposedPorts());
```
Comment (morazow) [inline src/main/java/com/exasol/containers/ExasolContainer.java:118]: Do you have to call `exposePorts()` here?

**Review by morazow — CHANGES_REQUESTED** [review]

File: src/main/java/com/exasol/containers/ExasolContainer.java (hunk 2 above)
Comment (jakobbraun) [reply src/main/java/com/exasol/containers/ExasolContainer.java:118]: it was a local method. Since I removed it's content, I also removed it from here

File: src/main/java/com/exasol/containers/ExasolContainer.java (hunk 1 above)
Comment (jakobbraun) [reply src/main/java/com/exasol/containers/ExasolContainer.java:161]: :+1:

**Review by morazow — APPROVED** [review]
