### PR TITLE
#258: Adapt to Exasol 8.29.1

### LINKED ISSUE #257: Container startup fails when using withExposedPorts()
When starting a container like this:

```java
try (final ExasolContainer<? extends ExasolContainer<?>> container = new ExasolContainer<>()) {
    container.withExposedPorts(8563).start();
    // use container
}
```

It will fail with the following exception:

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image exasol/docker-db:8.26.0
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:359)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:330)
        at com.exasol.containers.ExasolContainer.start(ExasolContainer.java:529)
        at com.exasol.containers.ExasolContainerSlcIT.testWithExposedPort(ExasolContainerSlcIT.java:32)
...
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:344)
        ... 73 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:563)
        at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:354)
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
        ... 74 more
Caused by: java.lang.NullPointerException
        at com.exasol.bucketfs.testcontainers.TestcontainerBucketFactory.mapPort(TestcontainerBucketFactory.java:67)
        at com.exasol.bucketfs.testcontainers.TestcontainerBucketFactory.lambda$0(TestcontainerBucketFactory.java:58)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at com.exasol.bucketfs.testcontainers.TestcontainerBucketFactory.getBucket(TestcontainerBucketFactory.java:48)
        at com.exasol.containers.ExasolContainer.getBucket(ExasolContainer.java:489)
        at com.exasol.containers.ExasolContainer.getBucket(ExasolContainer.java:470)
        at com.exasol.containers.ExasolContainer.getDefaultBucket(ExasolContainer.java:506)
        at com.exasol.containers.slc.ScriptLanguageContainerInstaller.create(ScriptLanguageContainerInstaller.java:39)
        at com.exasol.containers.ExasolContainer.installSlcIfNecessary(ExasolContainer.java:628)
        at com.exasol.containers.ExasolContainer.containerIsStarted(ExasolContainer.java:602)
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:542)
        ... 76 more
```

### Workaround
Omit `.withExposedPorts(8563)`.

### LINKED ISSUE #258: Container startup with Exasol 8.29.1 fails with NullPointerException
Startup of `exasol/docker-db:8.29.1` fails with the following exception:

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image exasol/docker-db:8.29.1
 at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:359)
 at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:330)
 at com.exasol.containers.ExasolContainer.start(ExasolContainer.java:529)
 at org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.start(TestcontainersExtension.java:280)
 at org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.access$200(TestcontainersExtension.java:267)
 at org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$null$4(TestcontainersExtension.java:82)
 at org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$startContainers$5(TestcontainersExtension.java:82)
 at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
 at org.testcontainers.junit.jupiter.TestcontainersExtension.startContainers(TestcontainersExtension.java:82)
 at org.testcontainers.junit.jupiter.TestcontainersExtension.beforeAll(TestcontainersExtension.java:56)
 at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
 at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
 at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:344)
 ... 60 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
 at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:563)
 at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:354)
 at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
 ... 61 more
Caused by: java.lang.NullPointerException
 at com.exasol.bucketfs.testcontainers.TestcontainerBucketFactory.mapPort(TestcontainerBucketFactory.java:67)
 at com.exasol.bucketfs.testcontainers.TestcontainerBucketFactory.lambda$0(TestcontainerBucketFactory.java:58)
 at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
 at com.exasol.bucketfs.testcontainers.TestcontainerBucketFactory.getBucket(TestcontainerBucketFactory.java:48)
 at com.exasol.containers.ExasolContainer.getBucket(ExasolContainer.java:489)
 at com.exasol.containers.ExasolContainer.getBucket(ExasolContainer.java:470)
 at com.exasol.containers.ExasolContainer.getDefaultBucket(ExasolContainer.java:506)
 at com.exasol.containers.slc.ScriptLanguageContainerInstaller.create(ScriptLanguageContainerInstaller.java:39)
 at com.exasol.containers.ExasolContainer.installSlcIfNecessary(ExasolContainer.java:628)
 at com.exasol.containers.ExasolContainer.containerIsStarted(ExasolContainer.java:602)
 at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:542)
 ... 63 more
```

## Root cause
The latest docker-db version uses TLS for BucketFS, which causes the observed error.

## Workaround
Please use docker-db 8.26.0 until this is fixed in exasol-testcontainers.

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #258

### CODE REVIEW

File: src/main/java/com/exasol/bucketfs/testcontainers/TestcontainerBucketFactory.java [hunk 1]
```diff
@@ -48,23 +53,42 @@ public synchronized Bucket getBucket(final String serviceName, final String buck
...
+                LOGGER.debug("Using encrypted BucketFS port {} (mapped to {})", serviceConfiguration.getHttpsPort(),
+                        mappedPort);
+                builder.port(mappedPort).useTls(true);
+            } else if (serviceConfiguration.getHttpPort() != 0) {
+                final int mappedPort = mapPort(serviceConfiguration.getHttpPort());
+                LOGGER.debug("Using unencrypted BucketFS port {} (mapped to {})", serviceConfiguration.getHttpPort(),
+                        mappedPort);
+                builder.port(mappedPort).useTls(false);
+            } else {
+                throw new IllegalStateException("Neither HTTPS nor HTTP port is defined");
```
Comment (ckunki) [inline src/main/java/com/exasol/bucketfs/testcontainers/TestcontainerBucketFactory.java:78]:
```suggestion
                throw new IllegalStateException("Neither HTTPS nor HTTP port is defined for BucketFS");
```

**Review by ckunki — APPROVED** [review]

**Review by ckunki — APPROVED** [review]
